---
- name: run show version on remote devices
  hosts: all
  gather_facts: no

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.nxos.nxos
    ansible_become: yes
    ansible_gecome_method: enable

  tasks:
    - name: run show version on remote devices using NXOS driver
      cisco.nxos.nxos_command:
        commands: show version