---
- name: Gather subset legacy facts and display them (Use tags config, hardware, interface, or min)
  hosts: devnet
  gather_facts: no

  tasks:
    - name: Gather config facts from IOS
      cisco.ios.ios_facts:
        gather_subset:
          - config
      register: ios_config_facts
      when: ansible_network_os == 'cisco.ios.ios'
      tags: config

    - name: Display IOS config facts
      debug: var=ios_config_facts
      tags: config

    - name: Gather config facts from NXOS devices
      cisco.nxos.nxos_facts:
        gather_subset:
          - hardware
      register: nxos_config_facts
      when: ansible_network_os == 'cisco.nxos.nxos'
      tags: config

    - name: Display NXOS config facts
      debug: var=nxos_config_facts
      tags: config

    # Gather hardware facts from IOS and NXOS devices
    - name: Gather hardware facts from IOS
      cisco.ios.ios_facts:
        gather_subset:
          - hardware
      register: ios_hardware_facts
      when: ansible_network_os == 'cisco.ios.ios'
      tags: hardware

    - name: Display IOS hardware facts
      debug: var=ios_hardware_facts
      tags: hardware

    - name: Gather hardware facts from NXOS devices
      cisco.nxos.nxos_facts:
        gather_subset:
          - hardware
      register: nxos_hardware_facts
      when: ansible_network_os == 'cisco.nxos.nxos'
      tags: hardware

    - name: Display NXOS hardware facts
      debug: var=nxos_hardware_facts
      tags: hardware


    # Gather interface facts from IOS and NXOS devices
    - name: Gather interface facts from IOS
      cisco.ios.ios_facts:
        gather_subset:
          - interface
      register: ios_interface_facts
      when: ansible_network_os == 'cisco.ios.ios'
      tags: interface

    - name: Display IOS hardware facts
      debug: var=ios_interface_facts
      tags: interface

    - name: Gather interface facts from NXOS devices
      cisco.nxos.nxos_facts:
        gather_subset:
          - interface
      register: nxos_interface_facts
      when: ansible_network_os == 'cisco.nxos.nxos'
      tags: interface

    - name: Display NXOS interface facts
      debug: var=nxos_interface_facts
      tags: interface