---
- name: Backup show version and other user level commands
  hosts: devnet_ios
  gather_facts: false

  tasks:
    - name: run multiple commands on remote devices
      ios_command:
        commands:
          - show run
          - show version
          - show ip arp
          - show ip protocols

      register: show_output

    - debug: var=show_output.stdout_lines

    - name: Create running config dir
      file:
        path: "output_files"
        state: directory
        recurse: yes
      run_once: yes

    - name: save output to file
      connection: local
      copy:
        content="\n ===show run=== \n {{ show_output.stdout[0] }}
                 \n ===show version=== \n {{ show_output.stdout[1] }}
                  \n ===show ip arp=== \n {{ show_output.stdout[2] }}
                  \n ===show ip protocols=== \n {{ show_output.stdout[3] }}"
        dest="./output_files/{{ inventory_hostname }}.txt"