- name: Gather loopback interface
  hosts: all
  gather_facts: no

  tasks:
    - name: configure Loopback interface settings for IOS devices
      cisco.ios.ios_config:
        lines:
          - description In-band management interface
          - ip address {{ loopback_10_address }}
        parents: interface Loopback10
      when: ansible_network_os=='cisco.ios.ios'


    - name: configure Loopback interface settings for NXOS devices
      cisco.nxos.nxos_config:
        lines:
          - description In-band management interface
          - ip address {{ loopback_10_address }}
        parents: interface loopback10
      when: ansible_network_os=='cisco.nxos.nxos'