- name: "Gather loopback interface"
  hosts: all
  gather_facts: no

  tasks:
    - name: configure Loopback interface settings
      cisco.ios.ios_config:
        lines:
          - description In-band management interface
          - ip address {{ loopback_10_address }}
        parents: interface Loopback10