- name: "Demonstrate connecting to switches of multiple types"
  hosts: all
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
    - name: Gather facts (nxos)
      cisco.nxos.nxos_facts:
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Gather facts (ios)
      cisco.ios.ios_facts:
      when: ansible_network_os == 'cisco.ios.ios'

    ###
    # Demonstrate variables
    #
    - name: Display some facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Facts from a specific host
      debug:
        var: hostvars['10.10.20.175']

    - name: Write facts to disk using an inline template
      copy:
        content: |
          #jinja2: lstrip_blocks: True
          NXOS device info:
            {% for host in groups['devnet_nxos'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}

          IOS device info:
            {% for host in groups['devnet_ios'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}
        dest: /tmp/switch-facts.txt
      run_once: yes

    - name: Create facts dir
      file:
        path: "/tmp/switch-facts"
        state: directory
        recurse: yes

    - name: Write facts to disk using a template file
      template:
        src: templates/facts_output.j2
        dest: /tmp/switch-facts/{{ inventory_hostname }}_facts.txt

    ###
    # Get running configuration
    #

    - name: Backup switch (nxos)
      cisco.nxos.nxos_config:
        backup: yes
      register: backup_nxos_location
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: backup switch (ios)
      cisco.ios.ios_config:
        backup: yes
      register: backup_ios_location
      when: ansible_network_os == 'cisco.ios.ios'

    - name: Create backup dir
      file:
        path: "/tmp/backups/{{ inventory_hostname }}"
        state: directory
        recurse: yes

    - name: Copy backup files into /tmp/backups/ (nxos)
      copy:
        src: "{{ backup_nxos_location.backup_path }}"
        dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.txt"
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Copy backup files into /tmp/backups/ (ios)
      copy:
        src: "{{ backup_ios_location.backup_path }}"
        dest: "/tmp/backups/{{ inventory_hostname }}/{{ inventory_hostname }}.txt"
      when: ansible_network_os == 'cisco.ios.ios'